"use strict";

const
  Assert = require('chai').assert,
  CamelCase = require('camelcase'),
  Plan = require('../../src/plan'),
  Plugins = require('../../src/plugins'),
  TestData = require('../data'),
  TestUtil = require('../util');

const { target, vizJs, jqueryCdnM } = TestData;

describe('Plugins.ScalaManifest', () => {

  it("generates a Scala manifest (local and data URLs only)", () => {
    const cfg = TestData.cfg({
      assets: {
        vizJs,
        svgs: { type: 'local', files: '*{1,2}.svg', manifest: CamelCase },
        wwJs: { type: 'external', path: '/ww.js', manifest: true },
        jquery: jqueryCdnM,
      },
      plugins: [
        Plugins.Inline.data(i => /image2/.test(i.dest)),
        Plugins.ScalaManifest({ object: "demo.test.Manifest" }),
      ],
    });
    const filename = "Manifest.scala"
    cfg.output.name = "[name]-[hash:16].[ext]";
    const state = Plan.run(cfg);
    Assert.deepEqual(state.errors, []);
    TestUtil.assertOps(state.ops, op => op.type === 'write' && op.to.path === filename, [{
      type: 'write',
      to: [target, filename],
      content: `
package demo.test

/** Generated by webtamp. */
object Manifest {

  def image1Svg = "/image1-03f43b8f2e62bd8d.svg";

  def image2Svg = "data:image/svg+xml;base64,aW1hZ2UyCg==";

  def vizJs = "/viz-e4e91995e194dd59.js";

  def wwJs = "/ww.js";
}
      `.trim()
    }]);
  });

});
