const term = n =>
  /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(n) ? n : "`" + n + "`";

const stringLiteral = s =>
  /["\n\r\t\\]/.test(s) ? `"""${s}"""` : `"${s}"`;

const plugin = ({ object, filename, nameMod = n => n }) => state => {

  const fqcn = object.match(/^(.+)\.([^.]+)$/);
  if (!fqcn) {
    state.addError(`Invalid object FQCN: ${objectName}`);
  } else {

    const [, pkg, obj] = fqcn;

    const defs = [];
    for (const k of Object.keys(state.manifest).sort()) {
      const v = state.manifest[k];
      // console.log(`${k} = ${require('../utils').inspect(v)}`)

      // Currently only captures local urls
      const url = v.local || v.url;
      if (url) {
        const name = nameMod(k);
        defs.push(`def ${term(name)} = ${stringLiteral(url)};`)
      }

      // final case class Resource(url: String, integrity: Option[String])
    }

    const content = [
      `package ${pkg}`,
      "",
      "/** Generated by webtamp. */",
      `object ${obj} {`,
      "",
      defs.map(l => `  ${l}`).join("\n\n"),
      "}"
    ].join("\n");

    // console.log("-------------------------------------------------------------------------")
    // console.log(content);
    // console.log("-------------------------------------------------------------------------")

    state.addOpWrite(filename || `${obj}.scala`, content);
  }
};

module.exports = plugin;
